In [5]:
import numpy as np

ndarray object

In [1]:
a=[1,2,3,4]

In [2]:
print(a)

[1, 2, 3, 4]


In [3]:
print(type(a))

<class 'list'>


In [6]:
np_a=np.array(a)

In [7]:
print(np_a)

[1 2 3 4]


In [9]:
print(type(np_a))

<class 'numpy.ndarray'>


In [11]:
L=range(1000)
%timeit [i**2 for i in L]

65.4 µs ± 3.13 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [12]:
a=np.arange(1000)
%timeit a**2

1.34 µs ± 52.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


creating arrays

In [13]:
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [14]:
a.ndim

1

In [15]:
a.shape

(4,)

In [17]:
b=np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
b.ndim

2

In [19]:
b.shape

(2, 3)

In [20]:
c=np.array([[[0,1],[2,3]],[[5,4],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[5, 4],
        [6, 7]]])

In [22]:
c.ndim

3

In [23]:
c.shape

(2, 2, 2)

Creating Numpy Arrays from list

In [24]:
list=[1,2,3]
list

[1, 2, 3]

In [26]:
np.array(list)

array([1, 2, 3])

In [27]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [28]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.array(my_matrix).shape

(3, 3)

functions for creating arrays


arange

In [32]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
b=np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

linespace

In [40]:
a=np.linspace(0,5,6)
a

array([0., 1., 2., 3., 4., 5.])

In [41]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

Zeros and Once

In [42]:
np.zeros(3)

array([0., 0., 0.])

In [43]:
b=np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [45]:
b=np.ones((4,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

creating identity matrix

In [46]:
c=np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
c=np.eye(3,2)
c

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [48]:
a=np.diag([7,8,4,3])
a

array([[7, 0, 0, 0],
       [0, 8, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 3]])

In [49]:
np.diag(a)

array([7, 8, 4, 3])

In [50]:
random_array=np.random.randint(1,121,5)
print(random_array)

[84 10 37 36 95]


In [51]:
a=np.random.rand(8)
a

array([0.64452112, 0.54921493, 0.54702993, 0.18881943, 0.80307371,
       0.37763699, 0.95653519, 0.41256163])

In [52]:
a=np.random.rand(50)
a

array([0.00831616, 0.75663562, 0.1002462 , 0.58364471, 0.41629551,
       0.01158603, 0.39737113, 0.35908249, 0.97706447, 0.95696499,
       0.32009809, 0.64392321, 0.679709  , 0.10245636, 0.7133351 ,
       0.26104295, 0.32907829, 0.85421898, 0.57062431, 0.93514607,
       0.64883878, 0.65841385, 0.19078495, 0.72301539, 0.74847823,
       0.75466157, 0.9732121 , 0.07265146, 0.64008231, 0.60942924,
       0.4654344 , 0.60366079, 0.92244369, 0.51169157, 0.60817602,
       0.51870358, 0.17070859, 0.28848784, 0.27482425, 0.81302093,
       0.07701549, 0.25386033, 0.71925454, 0.86395968, 0.46493512,
       0.64360088, 0.37281542, 0.75420455, 0.07705663, 0.3264907 ])

copy array

In [54]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [55]:
arr=np.arange(25)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


Reshape array

In [56]:
arr=np.arange(25)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [57]:
a1=arr.reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print("shape of a:",format(a.shape))

[[1 2 3]
 [4 5 6]]
shape of a: (2, 3)


Transpose of array

In [60]:
a=np.array([[1,2,3],[4,5,6]])
print("shape:".format(a.shape))
print(a)

shape:
[[1 2 3]
 [4 5 6]]


In [61]:
c=a.T
print(c)

[[1 4]
 [2 5]
 [3 6]]


flttening

In [62]:
a=np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

sorting

In [63]:
a=np.array([[5,4,6],[2,8,2]])
b=np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 2, 8]])

Add/Remove operations on a numpy array

In [64]:
a=np.array([4,7,8])
a=np.append(a,[2,4,5])
print(a)

[4 7 8 2 4 5]


In [65]:
a=np.delete(a,2)
print(a)

[4 7 2 4 5]


Indexing

In [66]:
a=np.arange(3,10)
print(a)
print(a[5])

[3 4 5 6 7 8 9]
8


In [67]:
a=np.diag([1,2,3])
print(a)
print(a[2,1])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
0


In [68]:
a[2,1]=5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

Slicing

In [69]:
a=np.arange(4,18)
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [70]:
a[1:8:2]

array([ 5,  7,  9, 11])

In [73]:
b=np.arange(10)
b[5:]

array([5, 6, 7, 8, 9])

In [74]:
b[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

fancy indexing

In [75]:
a=np.random.randint(0,20,5)
a

array([15,  1,  8, 19,  4])

In [76]:
a[a%2==0]

array([8, 4])

In [77]:
a[a%2==0]=-1
a

array([15,  1, -1, 19, -1])

indexing with an array of integers

In [78]:
a=np.arange(0,101,10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [79]:
a[[2,3,2,4,6]]

array([20, 30, 20, 40, 60])

In [81]:
a[[9,7]]=-200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200,  100])

operations

In [82]:
a=np.array([1,2,3,4])
print(a)
print(a+1)

[1 2 3 4]
[2 3 4 5]


In [83]:
a**2

array([ 1,  4,  9, 16])

All arithmetic operators elementwise

In [84]:
b=np.ones(4)+1
b

array([2., 2., 2., 2.])

In [85]:
a-b

array([-1.,  0.,  1.,  2.])

In [86]:
a*b

array([2., 4., 6., 8.])

In [87]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[4,4],[4,4],[4,4]])
print(a+b)

[[ 5  6]
 [ 7  8]
 [ 9 10]]


In [88]:
print(a*b)

[[ 4  8]
 [12 16]
 [20 24]]


In [7]:
c=np.diag([1,2,3,4])
print (c * c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [14]:
a=np.array([[1,2,1],[3,4,3],[5,6,5]])
b=np.array([[4,4,1],[4,4,2],[4,4,3]])
print("matrix multiplication is:\n",np.matmul(a,b))

matrix multiplication is:
 [[16 16  8]
 [40 40 20]
 [64 64 32]]


In [15]:
a=np.array([[1,2,1],[3,4,3],[5,6,5]])
b=np.array([[4,4,1],[4,4,2],[4,4,3]])
print("matrix multiplication is:\n",np.matmul(b,a))

matrix multiplication is:
 [[21 30 21]
 [26 36 26]
 [31 42 31]]


In [10]:
print(a*b)

[[ 4  8  1]
 [12 16  6]
 [20 24 15]]


In [11]:
print(b*a)

[[ 4  8  1]
 [12 16  6]
 [20 24 15]]


In [16]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
a==b

array([False,  True, False,  True])

In [25]:
a=np.array([1,2,6,4])
b=np.array([1,2,2,4])
c=np.array([1,2,6,4])

In [32]:
np.array_equal(a,b)

False

In [26]:
np.array_equal(a,c)

True

In [41]:
a=np.array([1,1,4,9],dtype=bool)
b=np.array([1,2,1,0],dtype=bool)
print (np.logical_or(a,b))
print (np.logical_and(a,b))
print(a+b)

[ True  True  True  True]
[ True  True  True False]
[ True  True  True  True]


In [40]:
a=np.array([1,1,0,0],dtype=float)
b=np.array([1,0,1,0],dtype=float)
#print (np.logical_or(a,b))
#print (np.logical_and(a,b))
print(a+b)

[2. 1. 1. 0.]


In [34]:
print(a+b)

[2 1 1 0]


In [31]:
a=np.array([1,1,0,0])
b=np.array([1,0,1,0])
print (np.logical_or(a,b))
print (np.logical_and(a,b))

[ True  True  True False]
[ True False False False]


In [33]:
print(a+b)

[2 1 1 0]


In [36]:
a=np.array([1,1,4,9],dtype=int)
b=np.array([1,2,1,0],dtype=int)
print (np.logical_or(a,b))
print (np.logical_and(a,b))
print(a+b)

[ True  True  True  True]
[ True  True  True False]
[2 3 5 9]


In [42]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [43]:
np.log(a)

C:\Users\soubh\AppData\Local\Temp\ipykernel_1316\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [44]:
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [45]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [49]:
a=np.array([[1,2,1],[3,4,3],[5,6,5]])
b=np.array([[4,1],[4,2],[4,4]])
print("matrix multiplication is:\n",np.matmul(b,a))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [50]:
x=np.array([1,4,5,2])
np.sum(x)

12

In [73]:
x=np.array([[2,1],[2,3]])
x

array([[2, 1],
       [2, 3]])

In [74]:
x.sum()

8

In [75]:
x.sum(axis=0)

array([4, 4])

In [76]:
x.sum()

8

In [77]:
x.sum(axis=1)


array([3, 5])

In [78]:
x.sum()

8

In [90]:
normal_array=np.arange(0,10,1)
print('Array is',format(normal_array))
#min
print('min element is',np.min(normal_array))
#max
print('max element is',np.max(normal_array))
#sum
print('sum element is',np.sum(normal_array))
#mean
print('mean element is',np.mean(normal_array))
#median
print('median element is',np.median(normal_array))
#sd
print('standard deviation element is',np.std(normal_array))

Array is [0 1 2 3 4 5 6 7 8 9]
min element is 0
max element is 9
sum element is 45
mean element is 4.5
median element is 4.5
standard deviation element is 2.8722813232690143
